# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-57d61f73-7174-47fe-824a-bbe2fddbc81d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-57d61f73-7174-47fe-824a-bbe2fddbc81d".device = "/dev/disk/by-uuid/57d61f73-7174-47fe-824a-bbe2fddbc81d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/08DE-67D1";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b1ec9b3e-09fd-480c-a929-5171b0241b06"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
