source=~/.cache/wal/hyprland.conf

background {
 path =/home/leo/Wallpapers/wallpaper.webp 
 blur_passes = 1
 blur_size = 7
  }

input-field {
    size= 200, 50
    outline_thckness = 3
    dots_size= 0.33
    dots_spacing = 0.15
    outer_color= color(rgb$color3)
    inner_color= color(rgb$color3)
    font_color= color(rgb$color3)

  }
