#!/usr/bin/env bash

function toggle_menu {
    MAIN=$(eww get main_monitor)
    hyprctl keyword blurls "remove,gtk-layer-shell"
    STATE=$(eww windows | grep $1$MAIN | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE == '*' ]]; then 
        if [[ $1 == 'powermenu' ]]; then
            hyprctl keyword blurls "remove,gtk-layer-shell"
        fi
        eww close $1$MAIN;
    else
        if [[ $1 == 'powermenu' ]]; then
            hyprctl keyword blurls "gtk-layer-shell"
        fi
        eww open $1$MAIN;
    fi
}

function close_osd {
    notify-send asd
}

picker() {
    COLOR=$(distrobox-enter -n Arch -- hyprpicker -n | grep "#") &&
    wl-copy --trim-newline $COLOR
    notify-send -i color-select-symbolic -a "Color Picker" $(wl-paste)
    echo $COLOR
}

function colorpicker {
    bash $HOME/.config/eww/scripts/launcher picker
}

function network {
    foot nmcli d wifi list
}

function screenlock {
    STATE0=$(eww windows | grep powermenu0 | awk '{print substr ($0, 0, 1)}')
    STATE1=$(eww windows | grep powermenu1 | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE0 == '*' ]]; then eww close powermenu0; fi
    if [[ $STATE1 == '*' ]]; then eww close powermenu1; fi
    
    hyprctl keyword blurls "gtk-layer-shell"
    gtklock -s $HOME/.config/gtklock/style.css
}

function notifications {
    kill -s USR1 $(pidof deadd-notification-center)
}

function config {
    lvim $HOME/.config/hypr
}

function screenshot {
    DIR="$HOME/Pictures/Screenshots"
    mkdir -p $DIR

    if [[ $1 == 'screen' ]]; then
        distrobox-enter -n Arch -- hyprshot -m output -o $DIR
    else
        distrobox-enter -n Arch -- hyprshot -m region -o $DIR
    fi
}

if [[ $1 == 'applauncher'    ]]; then tofi-drun --drun-launch=true; fi
if [[ $1 == 'pavu'           ]]; then pavucontrol; fi
if [[ $1 == 'network'        ]]; then network; fi
if [[ $1 == 'qctl'           ]]; then qjackctl; fi
if [[ $1 == 'brightness'     ]]; then wl-gammactl; fi
if [[ $1 == 'bluetooth'      ]]; then blueberry; fi
if [[ $1 == 'powermenu'      ]]; then powermenu; fi
if [[ $1 == 'notifications'  ]]; then notifications; fi
if [[ $1 == 'toggle_menu'    ]]; then toggle_menu $2; fi
if [[ $1 == 'close_menu'     ]]; then close_menu $2; fi
if [[ $1 == 'close_osd'      ]]; then close_osd; fi
if [[ $1 == 'close_calendar' ]]; then close_calendar; fi
if [[ $1 == 'colorpicker'    ]]; then colorpicker; fi
if [[ $1 == 'picker'         ]]; then hyprpicker; fi
if [[ $1 == 'screenlock'     ]]; then screenlock; fi
if [[ $1 == 'config'         ]]; then config; fi
if [[ $1 == 'screenshot'     ]]; then screenshot $2; fi
